services:
  - type: web
    name: amj-movies-searcher
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --config gunicorn.conf.py app:app
    envVars:
      - key: APP_ENV
        value: production
      - key: HOST
        value: 0.0.0.0
      - key: PORT
        value: 8000
      - key: SECRET_KEY
        generateValue: true
